use crate::prelude::*;

// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /home/mmoreiradj/git/crd-rs/crds/cilium/v2/ciliumcidrgroups.yaml --schema=derived -d --hide-prelude
// kopium version: 0.22.5

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug, JsonSchema)]
#[kube(
    group = "cilium.io",
    version = "v2",
    kind = "CiliumCIDRGroup",
    plural = "ciliumcidrgroups"
)]
pub struct CiliumCidrGroupSpec {
    /// ExternalCIDRs is a list of CIDRs selecting peers outside the clusters.
    #[serde(rename = "externalCIDRs")]
    pub external_cid_rs: Vec<String>,
}
