#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CRDS_DIR="$ROOT_DIR/crds/kubevirt"
CRDS_REL_DIR="crds/kubevirt"
CRATE_DIR="$ROOT_DIR/crates/kubevirt"
SRC_DIR="$CRATE_DIR/src"

if [ -z "${KUBEVIRT_REF:-}" ]; then
    KUBEVIRT_REF="$(gh release view --repo kubevirt/kubevirt --json tagName -q '.tagName')"
    echo "==> Resolved latest KubeVirt release: $KUBEVIRT_REF"
fi

# KubeVirt does not publish standalone CRD manifests: the per-resource CRDs
# (VirtualMachine, VirtualMachineInstance, ...) are generated by virt-operator
# at install time. We reproduce them deterministically by rendering the upstream
# generator functions from a checkout pinned at $KUBEVIRT_REF.

# CRD file -> module name mapping
declare -A CRDS=(
    ["virtualmachines.kubevirt.io.yaml"]="virtual_machine"
    ["virtualmachineinstances.kubevirt.io.yaml"]="virtual_machine_instance"
)

mkdir -p "$CRDS_DIR" "$SRC_DIR"

echo "$KUBEVIRT_REF" > "$CRDS_DIR/VERSION"
sed -i "s#^| \`crd-rs-kubevirt\` |.*#| \`crd-rs-kubevirt\` | [KubeVirt](https://github.com/kubevirt/kubevirt) | \`${KUBEVIRT_REF}\` |#" "$ROOT_DIR/README.md"

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

echo "==> Cloning kubevirt/kubevirt@${KUBEVIRT_REF}..."
git clone --depth 1 --branch "$KUBEVIRT_REF" https://github.com/kubevirt/kubevirt.git "$WORK_DIR/kubevirt" >/dev/null 2>&1

DUMP_DIR="$WORK_DIR/kubevirt/tools/dump-crds-crdrs"
mkdir -p "$DUMP_DIR"
cat > "$DUMP_DIR/main.go" <<'EOF'
package main

import (
	"fmt"
	"os"

	extv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/yaml"

	"kubevirt.io/kubevirt/pkg/virt-operator/resource/generate/components"
)

func write(path string, crd *extv1.CustomResourceDefinition, err error) {
	if err != nil {
		panic(err)
	}
	crd.TypeMeta = metav1.TypeMeta{
		APIVersion: "apiextensions.k8s.io/v1",
		Kind:       "CustomResourceDefinition",
	}
	out, err := yaml.Marshal(crd)
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(path, out, 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("  wrote %s (%d bytes)\n", path, len(out))
}

func main() {
	outDir := os.Args[1]

	vm, err := components.NewVirtualMachineCrd()
	write(outDir+"/virtualmachines.kubevirt.io.yaml", vm, err)

	vmi, err := components.NewVirtualMachineInstanceCrd()
	write(outDir+"/virtualmachineinstances.kubevirt.io.yaml", vmi, err)
}
EOF

echo "==> Rendering CRD schemas from upstream generators..."
(cd "$WORK_DIR/kubevirt" && GOFLAGS=-mod=vendor go run ./tools/dump-crds-crdrs "$CRDS_DIR")

echo "==> Generating Rust code with kopium..."

LIB_RS=""

for crd_file in "${!CRDS[@]}"; do
    mod_name="${CRDS[$crd_file]}"
    echo "  Generating module ${mod_name}..."
    # Generate without prelude, then prepend the crate-level prelude import
    (cd "$ROOT_DIR" && kopium -f "${CRDS_REL_DIR}/${crd_file}" --schema=derived -d --hide-prelude) > "${SRC_DIR}/${mod_name}.rs.tmp"
    {
        echo "use crate::prelude::*;"
        echo ""
        cat "${SRC_DIR}/${mod_name}.rs.tmp"
    } > "${SRC_DIR}/${mod_name}.rs"
    rm "${SRC_DIR}/${mod_name}.rs.tmp"
    LIB_RS="${LIB_RS}pub mod ${mod_name};\n"
done

# Write lib.rs with shared prelude and module declarations
cat > "${SRC_DIR}/lib.rs" <<'EOF'
#![allow(clippy::all)]

#[allow(unused_imports)]
mod prelude {
    pub use kube_derive::CustomResource;
    pub use schemars::JsonSchema;
    pub use serde::{Deserialize, Serialize};
    pub use std::collections::BTreeMap;
    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use k8s_openapi::apimachinery::pkg::util::intstr::IntOrString;
}

EOF

echo -e "$LIB_RS" >> "${SRC_DIR}/lib.rs"

# Create Cargo.toml only if missing, so manual version bumps survive regeneration
if [ ! -f "${CRATE_DIR}/Cargo.toml" ]; then
    cat > "${CRATE_DIR}/Cargo.toml" <<'EOF'
[package]
name = "crd-rs-kubevirt"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Kubernetes CRD bindings for KubeVirt"

[dependencies]
k8s-openapi = { workspace = true, features = ["schemars"] }
kube = { workspace = true, default-features = false, features = [] }
kube-core = { workspace = true, features = ["schema"] }
kube-derive.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
k8s-openapi = { workspace = true, features = ["latest", "schemars"] }
kube = { workspace = true, features = ["client", "rustls-tls"] }

[package.metadata.docs.rs]
features = ["k8s-openapi/latest"]
EOF
fi

echo "==> Formatting..."
cd "$ROOT_DIR"
cargo fmt -p crd-rs-kubevirt

echo "==> Running cargo check..."
K8S_OPENAPI_ENABLED_VERSION=1.32 cargo check -p crd-rs-kubevirt
echo "==> KubeVirt crate compiles successfully."
