use crate::prelude::*;

// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /home/mmoreiradj/git/crd-rs/crds/cnpg/postgresql.cnpg.io_clusterimagecatalogs.yaml --schema=derived -d --hide-prelude
// kopium version: 0.22.5

/// Specification of the desired behavior of the ClusterImageCatalog.
/// More info: <https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status>
#[derive(CustomResource, Serialize, Deserialize, Clone, Debug, JsonSchema)]
#[kube(
    group = "postgresql.cnpg.io",
    version = "v1",
    kind = "ClusterImageCatalog",
    plural = "clusterimagecatalogs"
)]
pub struct ClusterImageCatalogSpec {
    /// List of CatalogImages available in the catalog
    pub images: Vec<ClusterImageCatalogImages>,
}

/// CatalogImage defines the image and major version
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct ClusterImageCatalogImages {
    /// The image reference
    pub image: String,
    /// The PostgreSQL major version of the image. Must be unique within the catalog.
    pub major: i64,
}
