use crate::prelude::*;

// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /home/mmoreiradj/git/crd-rs/crds/cnpg/postgresql.cnpg.io_failoverquorums.yaml --schema=derived -d --hide-prelude
// kopium version: 0.22.5

/// Most recently observed status of the failover quorum.
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct FailoverQuorumStatus {
    /// Contains the latest reported Method value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,
    /// Primary is the name of the primary instance that updated
    /// this object the latest time.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub primary: Option<String>,
    /// StandbyNames is the list of potentially synchronous
    /// instance names.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "standbyNames"
    )]
    pub standby_names: Option<Vec<String>>,
    /// StandbyNumber is the number of synchronous standbys that transactions
    /// need to wait for replies from.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "standbyNumber"
    )]
    pub standby_number: Option<i64>,
}
