name: Release Drafter

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  cnpg:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-cnpg.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cilium:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-cilium.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
